/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tixr;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        assertNotNull("app should have a greeting", "placeholder!");
    }
}
