name: Publish latest and deploy
on:
  push:
    branches:
      - main

jobs:
  publish-dataplane-api:
    runs-on: ubuntu-latest
    env:
      OWNER: numberoverzero
      PRODUCT: tixr
      SURFACE: dataplane
      COMPONENT: api
    steps:
      -
        name: Configure meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ env.OWNER }}/${{ env.PRODUCT }}-${{ env.SURFACE }}-${{ env.COMPONENT }}
          tags: |
            type=raw,value=latest
            type=sha,format=long
      -
        name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      -
        name: Notify and deploy
        uses: numberoverzero/rook-action@v1
        with:
          endpoint: ${{ secrets.ROOK_ENDPOINT_DATAPLANE_API }}
          secret: ${{ secrets.ROOK_SECRET }}
          body: "ghcr.io/${{ env.OWNER }}/${{ env.PRODUCT }}-${{ env.SURFACE }}-${{ env.COMPONENT }}:sha-${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.revision'] }}"
